- hosts: localhost
  tasks:
  - name: Calling ansible api/v2/ping/ endpoint
    uri:
      url: "https://{{ ansible_tower_cluster }}/api/v2/ping/"
      method: GET
      validate_certs: False
    register: ping_output

  - name: Ping values
    debug:
      var: ping_output.stdout_lines
