- hosts: localhost
  tasks:
  - name: Including Vault Variables
    include_vars: vault.yml

  - name: Calling ansible api/v2/ping/ endpoint
    uri:
      url: "https://{{ ansible_tower_cluster }}/api/v2/ping/"
      method: GET
      validate_certs: False
    register: ping_output

  - name: Calling Ansible api/v2/config/ endpoint
    uri:
      url: "https://{{ ansible_tower_cluster }}/api/v2/config/"
      method: GET
      validate_certs: False
      user:     "{{ tower_user }}"
      password: "{{ tower_pass }}"
    register: config_output

  - name: API Output
    debug:
      var: "{{ item }}"
    with_items:
      - ping_output
      - config_output