- hosts: localhost
  tasks:
  - name: Calling ansible api/v2/ping/ endpoint
    uri:
      url: "https://{{ ansible_tower_cluster }}/api/v2/ping/"
      method: GET
      validate_certs: False
    register: ping_output

  - name: Calling Ansible api/v2/config/ endpoint
    uri:
      url: "https://{{ ansible_tower_cluster }}/api/v2/config/"
      method: GET
      validate_certs: False
      user:     "{{ tower_user }}"
      password: "{{ tower_pass }}"
      force_basic_auth: True
    register: config_output

  - name: API Output
    debug:
      msg: "{{ item.msg }}: {{ item.var }}"
    with_items:
      - { var: "{{ ping_output.json.instance_groups }}", msg: "Instance groups" }
      - { var: "{{ config_output.json.license_info.free_instances }}", msg: "Available Licenses" }
      - { var: "{{ config_output.json.license_info.instance_count }}", msg: "Total Licenses" }
